=== vijayakrishnan-sv/food-recipe-site/food-recipe-display-form/recipeSchema.json
{
	"definitions": {},
	"$schema": "http://json-schema.org/draft-07/schema#", 
	"title": "Root", 
	"type": "array",
	"default": [],
	"items":{
		"$id": "#root/items",  
		"title": "Recipes", 
		"type": "object",
        "required": [
			"name",
			"author",
			"prepTime",
			"cookTime",
			"ingredients",
			"description",
			"category",
			"serves",
			"image",
			"icon",
			"nutrients",
			"method"
		],
		"properties": {
			"name": {
				"title": "Name of the recipe", 
				"type": "string"
			},
			"author": {
				"title": "Author of recipe", 
				"type": "string"
			},
			"rating": {
				"title": "Rating", 
				"type": "string"
			},
			"prepTime": {
				"title": "Preparation time", 
				"type": "string"
			},
			"cookTime": {
				"title": "Cooking time", 
				"type": "string"
			},
			"ingredients": {
				"title": "Ingredients", 
				"type": "array",
				"default": [],
				"items":{
					"title": "Each ingredient", 
					"type": "string"
			
				}
			},
			"description": {
				"title": "Description", 
				"type": "string"
			},
			"category": {
				"title": "Category", 
				"type": "string"
			},
			"serves": {
				"title": "No of Serves", 
				"type": "string"
			},
			"image": {
				"title": "Recipe Image", 
				"type": "string"
			},
			"icon": {
				"title": "Recipe Icon", 
				"type": "string"
			},
			"nutrients": {
				"title": "Nutrients", 
				"type": "array",
				"default": [],
				"items":{
					"title": "Each Nutrient", 
					"type": "object",
					
					"properties": {
						"nutrient": {
							"title": "Kcal", 
							"type": "string"
						}
						
					}
				}

			},
			"method": {
				"title": "Method", 
				"type": "array",
				"default": [],
				"items":{
					"title": "Items", 
					"type": "string"
					
				}
			}
		}
	}

}

=== vijayakrishnan-sv/food-recipe-site/food-recipe-display-form/recipe.json
[
   {
       "name": "Herby spring chicken pot pie",
       "author": "Esther Clark",
       "rating": "58",
       "prepTime": "10 mins",
       "cookTime": "30 mins",
       "ingredients": [
           "2 tbsp olive oil",
           "bunch spring onions sliced into 3cm pieces",
           "250g frozen spinach",
           "6 ready-cooked chicken thighs",
           "350ml hot chicken stock",
           "½ tbsp wholegrain mustard",
           "200g frozen peas",
           "200ml half-fat crème fraîche",
           "½ small bunch tarragon leaves finely chopped",
           "small bunch parsley finely chopped",
           "270g pack filo pastry"
       ],
       "description": "Minimise your washing-up with this delicious one-pan chicken pie with spinach and herbs and topped with crispy filo pastry. It's ideal for busy weeknights",
       "category": "easy",
       "serves": "4",
       "image": "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/filopie-3972d72.jpg?quality=90&webp=true&resize=300,300",
       "icon": "meat.png",
       "nutrients": [
           {
               "kcal": "526"
           },
           {
               "fat": "22g"
           },
           {
               "saturates": "8g"
           },
           {
               "carbs": "47g"
           },
           {
               "sugars": "7g"
           },
           {
               "fibre": "7g"
           },
           {
               "protein": "32g"
           },
           {
               "salt": "1.3g"
           }
       ],
       "method": [
           "STEP 1\nHeat oven to 200C/180C fan/gas 6. Heat the oil in a large, shallow casserole dish on a medium heat. Add the spring onions and fry for 3 mins, then stir through the frozen spinach and cook for 2 mins or until it’s starting to wilt. Remove the skin from the chicken and discard. Shred the chicken off the bone and into the pan, and discard the bones. Stir through the stock and mustard. Bring to a simmer and cook, uncovered, for 5-10 mins.",
           "STEP 2\nStir in the peas, crème fraîche and herbs, then remove from the heat. Scrunch the filo pastry sheets over the mixture, brush with a little oil and bake for 15-20 mins or until golden brown."
       ]
   },
   {
       "name": "Bunny Carrot Cake",
       "author": "Esther Clark",
       "rating": "3",
       "prepTime": "30 mins",
       "cookTime": "70 mins",
       "ingredients": [
           "200g light soft brown sugar , plus 3 tbsp",
           "150ml light rapeseed oil (we used Cooks & Co with natural butter flavour), plus extra for greasing",
           "100g natural yogurt , plus extra to serve (optional)",
           "3 large eggs",
           "2 tsp vanilla extract",
           "zest 3 oranges",
           "300g self-raising flour",
           "1 tbsp mixed spice",
           "1 tsp ground cinnamon",
           "250g coarsely grated carrot",
           "crème fraîche , to serve (optional)",
           "225-250g small or baby carrots , peeled and halved lengthways",
           "juice 1 orange (from cake ingredients)",
           "25g butter",
           "4 tbsp light soft brown sugar"
       ],
       "description": "A sticky and delicious sponge with decorative candied carrot topping - enjoy a slice with a cup of coffee or tea",
       "category": "easy",
       "serves": "12",
       "icon": "cake.png",
       "image": "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/carrot-cake-b36f0fb.jpg?quality=90&amp;resize=300,300",
       "nutrients": [
           {
               "kcal": "359"
           },
           {
               "fat": "16g"
           },
           {
               "saturates": "3g"
           },
           {
               "carbs": "50g"
           },
           {
               "sugars": "32g"
           },
           {
               "fibre": "2g"
           },
           {
               "protein": "5g"
           },
           {
               "salt": "0.4g"
           }
       ],
       "method": [
           "STEP 1\n  First, make the caramelised carrots. Put the carrots in a saucepan so they can sit in just about a single layer. Add the orange juice, butter, sugar and enough water to cover the tops of the carrots by just 1cm. Bring to the boil, then cook until the water has almost evaporated and the carrots are left in a sticky syrup – you may want to reduce the heat if the liquid looks more syrupy, and go a little slower at the end so the carrots don’t catch. Can be made up to 1 day ahead.",
           "STEP 2\n  Heat oven to 160C/140C fan/gas 3. Grease a 23cm cake tin. Lift the candied carrots from the pan and syrup, and arrange in the base of the tin, cut-side down. Keep the pan and syrup for later.",
           "STEP 3\n  Whisk together the 200g brown sugar, the oil, yogurt, eggs, vanilla and zest from 2 oranges. Mix the flour, mixed spice, cinnamon and grated carrot in a big mixing bowl. Stir in the whisked mixture until smooth, then spoon over the carrots in the tin – be careful not to dislodge their arrangement too much. Bake for 45-50 mins until a skewer poked in comes out clean. Cool in the tin for 20 mins."
       ]
   },
   {
       "name": "Breakfast egg wraps",
       "author":"Sara Buenfeld",
       "rating":"40",
       "prepTime": "5 mins",
       "cookTime": "7 mins",
       "ingredients": [
           "500g pack closed cup mushrooms",
           "4 tsp rapeseed oil , plus 2 drops",
           "320g cherry tomatoes , halved, or 8 tomatoes, cut into wedges",
           "2 generous handfuls parsley , finely chopped",
           "8 tbsp porridge oats (40g)",
           "10 eggs",
           "4 tsp English mustard powder made up with water"
       ],
       "description" : "Enjoy these protein-rich egg wraps filled with mushrooms and tomatoes for a quick, filling and healthy breakfast. It provides iron, folate and fibre.",
       "category": "easy",
       "serves": "4",
       "icon": "breakfast.png",
       "image": "https://images.immediate.co.uk/production/volatile/sites/30/2020/05/breakfast-egg-wraps-c0880fe.jpg?quality=90&amp;resize=300,300",
       "nutrients": [
           {
               "kcal": "429"
           },
           {
               "fat": "20g"
           },
           {
               "saturates": "4g"
           },
           {
               "carbs": "31g"
           },
           {
               "sugars": "4g"
           },
           {
               "fibre": "6g"
           },
           {
               "protein": "28g"
           },
           {
               "salt": "0.55g"
           }
       ],
       "method": [
           "STEP 1\nThickly slice half the pack of mushrooms. Heat 2 tsp rapeseed oil in a non-stick pan. Add the mushrooms, stir briefly then fry with the lid on the pan for 6-8 mins. Stir in half the tomatoes then cook 1-2 mins more with the lid off until softened.",
           "STEP 2\n Beat together the eggs really well with the parsley and oats. Heat a drop of oil in a large non-stick frying pan. Pour in a ¼ of the egg mix and fry for 1 min until almost set, flip over as if making a pancake. Tip from the pan, spread with a quarter of the mustard, spoon a ¼ the filling down the centre and roll up. Now make a second wrap using another ¼ of the egg mix and filling. If you're following our Healthy Diet Plan, save the rest for the following day."
       ]
   },
   {
       "name": "Fish Mappas",
       "author" : "Good Food team",
       "rating" : "101",
       "prepTime": "15 mins",
       "cookTime": "30 mins",
       "ingredients": [
           "300g basmati rice",
           "1 tbsp sunflower or vegetable oil",
           "2 large onions , sliced",
           "2 garlic cloves , chopped",
           "450g tomatoes , cut into chunks",
           "3 tbsp tikka curry paste",
           "400g can coconut milk",
           "4 skinless, boneless pollock fillets (about 150g/51/2oz each), or other sustainable white fish, cut into 4cm/11/2in chunks",
           "½ small pack coriander , roughly chopped"
       ],
       "description" : "A coconut fish curry, popular in the southern Indian state of Kerala - use pollock or any other sustainably sourced white fish fillets",
       "category": "easy",
       "serves": "4",
       "icon": "fish.png",
       "image": "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/fish-mappas-a84eed1.jpg?quality=90&amp;resize=300,300",
       "nutrients": [
           {
               "kcal": "691"
           },
           {
               "fat": "26g"
           },
           {
               "saturates": "16g"
           },
           {
               "carbs": "74g"
           },
           {
               "sugars": "11g"
           },
           {
               "fibre": "4g"
           },
           {
               "protein": "39g"
           },
           {
               "salt": "0.8g"
           }
       ],
       "method": [
           "STEP 1\n  Put a large saucepan of water on to boil and cook the rice following pack instructions. Meanwhile, heat the oil in a large, wide saucepan over a medium heat and add the onions. Cook for 5-10 mins until softened and starting to colour. Add the garlic and tomatoes, and fry for 2 mins. Add the curry paste, fry for 2 mins more, then pour in the coconut milk and bring to the boil.",
           "STEP 2\n  Add the fish to the pan and simmer gently for 5-8 mins until just cooked through. Turn off the heat. Sprinkle the coriander over the curry and serve with the rice."
       ]
   },
   {
       "name": "Teriyaki prawns & broccoli noodles",
       "author" :"Good Food team",
       "rating" : "7",
       "prepTime": "10 mins",
       "cookTime": "10 mins",
       "ingredients": [
           "50ml low-sodium soy sauce",
           "50ml mirin",
           "2 tbsp lemon juice",
           "1 ½ tbsp caster sugar",
           "200g soba noodle",
           "140g thin-stemmed broccoli",
